### ISSUE TITLE
Components in Figma asset missing from codebase

### ISSUE THREAD

**Issue by mateoclarke** [18F/identity-design-system#380]
Howdy 👋

I'm an Engineer at MO Studio working on a project for the VA related to In-Person Identity Proofing for Login.gov accounts. We're using this design system on top of USWDS for our prototype. 

Our designers have access to the `2023-10-VA_Request-LGDS_Design_Assets` project in Figma and have used these two components in mockups that we can't identify in the library code. They are the "Step Indicator" and "List Link Item" components screen captured below:

![Screenshot 2023-11-06 at 3 09 52 PM](https://github.com/18F/identity-design-system/assets/5697474/a9171409-16ca-4f18-91e9-4cf20723e8ee)

![Screenshot 2023-11-06 at 3 10 08 PM](https://github.com/18F/identity-design-system/assets/5697474/29dc335b-9833-4336-b67e-92d8bbaf4d05)

The step indicator works with USWDS styling but seems to be missing LGDS styles to extend it. The List Link seems like its unique to LGDS. Can you point us to any docs or examples of these components? Even just the CSS for them would help us implement them as custom components for now.

Thanks for reviewing and for all the work that goes into building and maintaining this project!

~ Mateo

**Comment by aduth** [comment]
Hi @mateoclarke , apologies for the fragmentation. These components are implemented in the [main "IdP" application](https://github.com/18F/identity-idp) and haven't been fully backported to this repository yet.

In the meantime, will the following links work for you?

* Block Link (Link List Item)
   * Ruby on Rails [ViewComponent](https://viewcomponent.org/) Component:
      * Back-end: https://github.com/18F/identity-idp/blob/main/app/components/block_link_component.rb
      * Front-end: https://github.com/18F/identity-idp/blob/main/app/components/block_link_component.html.erb
   * React component: https://github.com/18F/identity-idp/blob/main/app/javascript/packages/components/block-link.tsx
   * Stylesheet: https://github.com/18F/identity-idp/blob/main/app/assets/stylesheets/components/_block-link.scss
   * Preview: https://idp.dev.identitysandbox.gov/components/inspect/block_link/preview
* Step indicator
   * Ruby on Rails [ViewComponent](https://viewcomponent.org/) Component:
      * Back-end:
         * Step indicator: https://github.com/18F/identity-idp/blob/main/app/components/step_indicator_component.rb
         * Step indicator step: https://github.com/18F/identity-idp/blob/main/app/components/step_indicator_step_component.rb
      * Front-end:
         * Step indicator: https://github.com/18F/identity-idp/blob/main/app/components/step_indicator_component.html.erb
         * Step indicator step: https://github.com/18F/identity-idp/blob/main/app/components/step_indicator_step_component.html.erb
   * JavaScript (including React component and custom element): https://github.com/18F/identity-idp/tree/main/app/javascript/packages/step-indicator       
   * Stylesheet: https://github.com/18F/identity-idp/blob/main/app/assets/stylesheets/components/_step-indicator.scss
   * Preview: https://idp.dev.identitysandbox.gov/components/inspect/step_indicator/preview

**Comment by mateoclarke** [comment]
Awesome, thanks for this thorough response Andrew! These examples are exactly what we were hoping for! I'll go ahead and close this issue and reopen if any follow-up questions come up. Appreciate y'all!

**Comment by mateoclarke** [comment]
Hey friends, just wanted to follow up an say we were successful in importing the core "step-indicator" components into our project! 🎉

![Screenshot 2023-11-29 at 7 52 57 PM](https://github.com/18F/identity-design-system/assets/5697474/a85cbfe1-1672-4ec4-b91d-c8c2c79230ed)

We'll be working on importing "block-link" soonish.

**Comment by aduth** [comment]
Great to hear @mateoclarke ! Hopefully in the near future we can prioritize getting these styles made available directly through the design system so you wouldn't need to duplicate them in your own project using the styles from `identity-idp`.
